### ISSUE TITLE
error: Input variable errors

### ISSUE THREAD

**Issue by razasaleem** [digitickets/omnipay-paymentsense#5]
Hello, anyone there?
I have an error of "Input variable errors". Here is my code kindly help me out. thanks

$gateway = Omnipay::create('\Coatesap\PaymentSense\Gateway');
$formData = array(
                'firstName' => 'Example',
                'lastName' => 'User',
                'number' => '4111111111111111',
                'expiryMonth' => '12',
                'expiryYear' => '2018',
                'cvv' => '123',
                'issueNumber' => '5',
                'startMonth' => '4',
                'startYear' => '2015',
            );
$response = $gateway->purchase(array('amount' => '10.00', 'currency' => 'GBP', 'card' => $formData))->send();

if ($response->isRedirect()) {
    // redirect to offsite payment gateway
    $response->redirect();
} elseif ($response->isSuccessful()) {
    // payment was successful: update database
    print_r($response);
} else {
    // payment failed: display message to customer
    echo $response->getMessage();//print_r($response);
}

**Comment by coatesap** [comment]
Hi, are you configuring your `$gateway` object, prior to calling `purchase()`?

**Comment by coatesap** [comment]
Also, from the documentation:

**Error 30 Variable Input Error**
Please check that you are using the correct Gateway Details not the Merchant Management System login details.

**Comment by Faizanq** [comment]
am also facing the same issue, has anyone resolved this?

**Comment by Faizanq** [comment]
Resolved by Adding the OrderId parameter.
